### ISSUE TITLE
Could this be considered an SDK?

### ISSUE THREAD

**Issue by foldl** [openai/openai-realtime-embedded-sdk#4]
A report generated by `cloc *`:

| Language | files | blank | comment | code |
|----------|-------|-------|---------|------|
| C++      | 5     | 59    | 4       | 358  |
| CMake    | 3     | 17    | 3       | 61   |
| Markdown | 1     | 17    | 0       | 31   |
| C/C++ Header | 1 | 2 | 0 | 11 |
| CSV      | 1 | 1 | 0 | 5 |
| YAML     | 1 | 0 | 0 | 3 |

**Comment by juberti-oai** [comment]
It's more sample code than a SDK per se, but... why do you ask?

**Comment by foldl** [comment]
An accurate name helps us to understand what's going on. I am wondering if I missed something or not when this is called an SDK.

**Comment by juberti-oai** [comment]
I'm still a bit confused as to the meaning of the language statistics from the original post, but yeah, this is essentially a demonstration of how to use the WebRTC Realtime API from an ESP32 device.

**Comment by foldl** [comment]
Got it.
